ckanext/versions/blueprints.py
from ckan import model
from ckan.lib import helpers as h
from ckan.plugins import toolkit
from flask import Blueprint

versions = Blueprint('versions', __name__)


def changes(id):
    context = {
        'model': model, 'user': toolkit.c.user
    }

    try:
        # We'll need this for the title / breadcrumbs, etc
        current_pkg_dict = toolkit.get_action('package_show')(
            context, {'id': id})
    except toolkit.NotAuthorized:
        toolkit.abort(401, 'Not authorized to read dataset')

    versions = toolkit.get_action('dataset_version_list')(
        context, {'dataset': id})

    version_id_1 = toolkit.request.args.get('version_id_1')
    version_id_2 = toolkit.request.args.get('version_id_2')

    if version_id_1 and version_id_2:
        try:
            diff = toolkit.get_action('dataset_versions_diff')(
                context, {
                    'id': id,
                    'version_id_1': version_id_1,
                    'version_id_2': version_id_2,
                    'diff_type': 'html',
                }
            )
        except (toolkit.ValidationError, toolkit.ObjectNotFound) as e:
            h.flash_error(toolkit._('Errors found: {}').format(e))
            return toolkit.render(
                'package/version_changes.html', {
                    'pkg_dict': current_pkg_dict,
                    'versions': versions
                }
            )
    else:
        diff = None

    return toolkit.render(
        'package/version_changes.html', {
            'diff': diff,
            'pkg_dict': current_pkg_dict,
            'versions': versions,
            'version_id_1': version_id_1,
            'version_id_2': version_id_2,
        }
    )


versions.add_url_rule('/dataset/<id>/version/changes', view_func=changes)

ckanext/versions/logic/auth.py
# encoding: utf-8
from ckan.authz import is_authorized
from ckan.plugins import toolkit


def dataset_version_create(context, data_dict):
    """Check if a user is allowed to create a version

    This is permitted only to users who are allowed to modify the dataset
    """
    return is_authorized('package_update', context,
                         {"id": data_dict['dataset']})


def dataset_version_delete(context, data_dict):
    """Check if a user is allowed to delete a version

    This is permitted only to users who are allowed to modify the dataset
    """
    return is_authorized('package_update', context,
                         {"id": data_dict['dataset']})


@toolkit.auth_allow_anonymous_access
def dataset_version_list(context, data_dict):
    """Check if a user is allowed to list dataset versions

    This is permitted only to users who can view the dataset
    """
    return is_authorized('package_show', context, {"id": data_dict['dataset']})


@toolkit.auth_allow_anonymous_access
def dataset_version_show(context, data_dict):
    """Check if a user is allowed to view dataset versions

    This is permitted only to users who can view the dataset
    """
    return is_authorized('package_show', context, {"id": data_dict['dataset']})


@toolkit.auth_allow_anonymous_access
def dataset_versions_diff(context, data_dict):
    return dataset_version_show(context, data_dict)

ckanext/versions/templates/package/read.html
{% ckan_extends %}

{% block content_action %}
  {% if not c.current_version %}
    {{ super() }}
  {% endif %}
{% endblock %}

{% block page_heading %}
  {{ super() }}
  {% if c.current_version %}
  <span class="label label-default">version {{ c.current_version.name }}</span>
  {% endif %}
{% endblock %}

{% block package_description %}
  {{ super() }}
  {% if c.current_version %}
  <p>{{ c.current_version.description }}</p>
  {% endif %}
{% endblock %}

{% block primary_content_inner %}
  {{ super() }}
  {% block versions_list %}
    {% snippet "package/snippets/versions_list.html", pkg=pkg %}
  {% endblock %}
{% endblock %}

{% block package_revision_info %}
  {% if c.current_version %}
    <div class="module info alert alert-info">
      <p class="module-content">
        {% set timestamp = h.render_datetime(c.revision_date, with_hours=True) %}
        {% set url = h.url_for(controller='package', action='read', id=pkg.id) %}

        {% trans timestamp=timestamp, url=url %}This is an old version of this dataset, as edited at {{ timestamp }}. It may differ significantly from the <a href="{{ url }}">current version</a>.{% endtrans %}
      </p>
    </div>
  {% else %}
    {{ super() }}
  {% endif %}
{% endblock %}

ckanext/versions/templates/package/resource_read.html
{% ckan_extends %}

{% block resource_actions_inner %}
  {% if not c.current_version and h.check_access('package_update', {'id':pkg.id }) %}
    <li>{% link_for _('Manage'), controller='package', action='resource_edit', id=pkg.name, resource_id=res.id, class_='btn btn-default', icon='wrench' %}</li>
  {% endif %}
  {% if res.url and h.is_url(res.url) %}
    <li>
      <div class="btn-group">
      <a class="btn btn-primary resource-url-analytics resource-type-{{ res.resource_type }}" href="{{ res.url }}">
        {% if res.resource_type in ('listing', 'service') %}
          <i class="fa fa-eye"></i> {{ _('View') }}
        {% elif  res.resource_type == 'api' %}
          <i class="fa fa-key"></i> {{ _('API Endpoint') }}
        {% elif (not res.has_views or not res.can_be_previewed) and not res.url_type == 'upload' %}
          <i class="fa fa-external-link"></i> {{ _('Go to resource') }}
        {% else %}
          <i class="fa fa-arrow-circle-o-down"></i> {{ _('Download') }}
        {% endif %}
      </a>
        {% block download_resource_button %}
          {{ super() }}
        {% endblock %}
      </div>
    </li>
  {% endif %}
{% endblock %}

{% block resource_content %}
  {% block package_revision_info %}
    {% if c.current_version and res.revision_timestamp %}
      <div class="module info alert alert-info">
        <p class="module-content">
          {% set timestamp = h.render_datetime(res.revision_timestamp, with_hours=True) %}
          {% set url = h.url_for(controller='package', action='read', id=pkg.id) %}
          {% trans timestamp=timestamp, url=url %}
            This resource is from an old revision of this dataset, as edited at {{ timestamp }}.
            It may differ significantly from the <a href="{{ url }}">current revision of the dataset</a>.
          {% endtrans %}
        </p>
      </div>
    {% endif %}
  {% endblock %}

  {{ super() }}
{% endblock %}

{% block resource_read_title %}
  <h1 class="page-heading">{{ h.resource_display_name(res) | truncate(50) }}
  {% if c.current_version %}
    <span class="label label-default">version {{ c.current_version.name }}</span>
  {% endif %}
  </h1>
{% endblock %}

{% block data_preview %}
  {% if c.current_version %}
    <div class="module warning alert alert-warning">
      {{ _('Data preview is not available for this revision of the data; You can still download the resource and view it locally.') }}
    </div>
  {% else %}
    {{ super() }}
  {% endif %}
{% endblock %}

ckanext/versions/templates/package/snippets/additional_info.html
{% ckan_extends %}

{% block extras %}

  {% if c.current_version %}
      <tr>
        <th scope="row" class="dataset-label">{{ _("Version Created") }}</th>
        <td class="dataset-details">
            {% snippet 'snippets/local_friendly_datetime.html', datetime_obj=c.current_version.created %}
        </td>
      </tr>
      <tr>
        <th scope="row" class="dataset-label">{{ _("Version Updated") }}</th>
        <td class="dataset-details">
            {% snippet 'snippets/local_friendly_datetime.html', datetime_obj=c.current_version.created %}
        </td>
      </tr>
  {% endif %}

  {{ super() }}

{% endblock %}

ckanext/versions/templates/package/snippets/change_item.html
<h3>Changes Summary</h3>

{% set changes = h.dataset_version_compare_pkg_dicts(diff.dataset_dict_1, diff.dataset_dict_2, 'xxx') %}
<ul>
{% for change in changes %}
  {% snippet "snippets/changes/{}.html".format(
    change.type), change=change %}
  <br>
{% endfor %}
</ul>

ckanext/versions/templates/package/snippets/compare_versions.html
<div class="modal fade" id="compareVersionsModal" tabindex="-1" role="dialog" aria-labelledby="compareVersionsModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <form class="compare-versions-form" action="{{ h.url_for('versions.changes', id=pkg.name) }}">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="compareVersionsModalLabel">Compare versions of dataset {{ pkg.title }}</h4>
          </div>
          <div class="modal-body">
            View changes from
              <select class="form-control select-time" name="version_id_1">
                {# Skip the most recent one in the from field #}
                {% snippet 'package/snippets/versions_select_options.html', versions=c.versions, selected_id=version_id_1 %}
              </select> to
              <select class="form-control select-time" name="version_id_2">

                {% snippet 'package/snippets/versions_select_options.html', versions=c.versions, selected_id=version_id_2, include_current=True %}
              </select>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
            <button type="submit" class="btn btn-primary">Compare</button>
          </div>
        </form>
      </div>
    </div>
  </div>

ckanext/versions/templates/package/snippets/create_version.html
<!-- Modal -->
<div class="modal fade" id="createVersionModal" tabindex="-1" role="dialog" aria-labelledby="createVersionModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <form class="create-version-form">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="createVersionModalLabel">Create a new version pointing to the current state of this dataset</h4>
          </div>
          <div class="modal-body">
            <div class="form-group">
              <label for="version_name">Version name</label>
              <input type="text" class="form-control" id="version_name" name="version_name" placeholder="version 1.2" required>
            </div>
            <div class="form-group">
              <label for="version-details">Description</label>
              <textarea id="version-details" name="details" class="form-control" rows="3"></textarea>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
            <button type="submit" class="btn btn-primary">Create Version</button>
          </div>
        </form>
      </div>
    </div>
  </div>

ckanext/versions/templates/package/snippets/resource_item.html
{% ckan_extends %}

{% if c.current_version %}
  {% set can_edit = False %}
{% endif %}

{% block resource_item_title %}
  {% if not url_is_edit %}
    {% set url = h.url_for_version(pkg, controller='package', action='resource_read', resource_id=res.id, version=c.current_version) %}
  {% endif %}
  <a class="heading" href="{{ url }}" title="{{ res.name or res.description }}">
    {{ h.resource_display_name(res) | truncate(50) }}<span class="format-label" property="dc:format" data-format="{{ res.format.lower() or 'data' }}">{{ h.get_translated(res, 'format') }}</span>
    {{ h.popular('views', res.tracking_summary.total, min=10) }}
  </a>
{% endblock %}

{# This is copied here because I have no way to nicely override
   just the part I need which is to replace the resource URL
   with a revision aware one :(
#}
{% block resource_item_explore_links %}
  {% set url = h.url_for_version(pkg, controller='package', action='resource_read', resource_id=res.id, version=c.current_version) %}
  <li>
    <a href="{{ url }}">
      {% if res.has_views %}
        <i class="fa fa-bar-chart-o"></i>
        {{ _('Preview') }}
      {% else %}
        <i class="fa fa-info-circle"></i>
        {{ _('More information') }}
      {% endif %}
    </a>
  </li>
  {% if res.url and h.is_url(res.url) %}
  <li>
    <a href="{{ res.url }}" class="resource-url-analytics" target="_blank">
      {% if res.has_views or res.url_type == 'upload' %}
        <i class="fa fa-arrow-circle-o-down"></i>
        {{ _('Download') }}
      {% else %}
        <i class="fa fa-external-link"></i>
        {{ _('Go to resource') }}
      {% endif %}
    </a>
  </li>
  {% endif %}
  {% if can_edit %}
  <li>
    <a href="{{ h.url_for(controller='package', action='resource_edit', id=pkg.name, resource_id=res.id) }}">
      <i class="fa fa-pencil-square-o"></i>
      {{ _('Edit') }}
    </a>
  </li>
  {% endif %}
{% endblock %}

ckanext/versions/templates/package/snippets/resource_view.html
{% ckan_extends %}

{# Had to override the entire snippet as it is not devided to any meaningful blocks #}

{% set view_url = h.url_for_version(package, resource_id=resource['id'], view_id=resource_view['id'], qualified=True, route_name='resource_view', version=c.current_version) %}

{% block resource_view %}
  <div id="view-{{ resource_view['id'] }}" class="resource-view" data-id="{{ resource_view['id'] }}" data-title="{{ resource_view['title'] }}" data-description="{{ resource_view['descripion'] }}">
  <div class="actions">
    <a class="btn btn-default"
       target="_blank"
       href="{{ view_url }}">
      <i class="fa fa-arrows-alt"></i>
      {{ _("Fullscreen") }}
    </a>
    <a class="btn btn-default"
       href="#embed-{{ resource_view['id'] }}"
       data-module="resource-view-embed"
       data-module-id="{{ resource_view['id'] }}"
       data-module-url="{{ view_url }}">
      <i class="fa fa-code"></i>
      {{ _("Embed") }}
    </a>
  </div>
  <p class="desc">{{ h.render_markdown(resource_view['description']) }}</p>
    <div class="m-top ckanext-datapreview">
      {% if not to_preview and h.resource_view_is_filterable(resource_view) %}
        {% snippet 'package/snippets/resource_view_filters.html', resource=resource %}
      {% endif %}
      {% if not h.resource_view_is_iframed(resource_view) %}
        {{ h.rendered_resource_view(resource_view, resource, package) }}
      {% else %}
        <div class="data-viewer-error js-hide">
          <p class="text-danger">
            <i class="fa fa-info-circle"></i>
            {{ _('This resource view is not available at the moment.') }}
            <a href="#" data-toggle="collapse" data-target="#data-view-error">
              {{ _('Click here for more information.') }}
            </a>
          </p>
          <p id="data-view-error" class="collapse"></p>
          <p>
            <a href="{{ resource.url }}" class="btn btn-default btn-lg resource-url-analytics" target="_blank">
              <i class="fa fa-lg fa-arrow-circle-o-down"></i>
              {{ _('Download resource') }}
            </a>
          </p>
        </div>
        {% if not to_preview %}
          {% set current_filters = request.str_GET.get('filters') %}
          {% if current_filters %}
            {% set src = h.url_for_version(package, version=c.current_version,
                                           qualified=true, controller='package',
                                           action='resource_view',
                                           resource_id=resource['id'],
                                           view_id=resource_view['id'],
                                           filters=current_filters) %}
          {% else %}
            {% set src = view_url %}
          {% endif %}
        {% else %}
          {# When previewing we need to stick the whole resource_view as a param as there is no other way to pass to information on to the iframe #}
          {% set src = h.url_for_version(package, version=c.current_version, qualified=true, controller='package', action='resource_view', resource_id=resource['id'], resource_view=h.dump_json(resource_view)) %}
        {% endif %}
        <iframe src="{{ src }}" frameborder="0" width="100%" data-module="data-viewer">
          <p>{{ _('Your browser does not support iframes.') }}</p>
        </iframe>
      {% endif %}
    </div>
    <div id="embed-{{ resource_view['id'] }}" class="modal fade resource-view-embed">
      <div class="modal-dialog">
    <div class="modal-content">

      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h3>{{ _("Embed resource view") }}</h3>
      </div>
      <div class="modal-body">
        <p class="embed-content">{{ _("You can copy and paste the embed code into a CMS or blog software that supports raw HTML") }}</p>
        <div class="row">
          <div class="col-md-6">
            {{ form.input("width", label=_("Width"), value=700, classes=["control-full"]) }}
          </div>
          <div class="col-md-6">
            {{ form.input("height", label=_("Height"), value=400, classes=["control-full"]) }}
          </div>
        </div>
        {{ form.textarea("code", label=_("Code"), value="", classes=["pre"], rows=3) }}
      </div>
      </div>
      </div>
    </div>
  </div>
{% endblock %}

ckanext/versions/templates/package/snippets/update_version.html
<!-- Modal -->
<div class="modal fade" id="updateVersionModal" tabindex="-1" role="dialog" aria-labelledby="updateVersionModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <form class="update-version-form">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="updateVersionModalLabel">Edit Version {{ c.current_version.name }} of dataset {{ c.pkg.name }}</h4>
          </div>
          <div class="modal-body">
            <div class="form-group">
              <label for="version_name">Version name</label>
              <input type="text" class="form-control" id="version_name" name="version_name" placeholder="version 1.2" value="{{ c.current_version.name }}" required>
            </div>
            <div class="form-group">
              <label for="version-details">Description</label>
              <textarea id="version-details" name="details" class="form-control" rows="3">{{ c.current_version.description }}</textarea>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
            <button type="submit" class="btn btn-primary">Save Changes</button>
          </div>
        </form>
      </div>
    </div>
  </div>

ckanext/versions/templates/package/snippets/versions_list.html
{% set pkg = c.pkg_dict %}
{% set versions = c.versions %}
{% resource 'versions/dataset_versions.js' %}

<div id="versions-container"
    data-module="dataset_version_controls"
    data-module-api-url="{{ h.url_for('api.action', ver=3, logic_function='') }}"
    data-module-package-id="{{ pkg.id }}"
    data-module-package-url="{{ h.url_for(controller='package', action='read', id=pkg.name) }}"
    data-module-link-resources="{{ h.dataset_version_has_link_resources(pkg) }}"
    {% if c.current_version %}
        data-module-version-id="{{ c.current_version.id }}"
    {% endif %}>

  {% if not c.revision_date %}
    <h3>Versions</h3>
    {% if versions | length > 0 %}
      <table class="table table-striped table-bordered table-condensed">
        <thead>
          <tr>
            <th scope="col">Version</th>
            <th scope="col">Description</th>
            <th scope="col">Published</th>
          </tr>
        </thead>
        <tbody>
        {% for version in versions %}
          <tr>
            <th scope="row" class="dataset-label">
              <a href="{{ h.url_for_version(pkg, version=version, controller='package', action='read') }}">
                {{ version.name }}
              </a>
            </th>
            <td class="dataset-details">
              {{ version.description }}
            </td>
            <td class="dataset-details">
              {% snippet 'snippets/local_friendly_datetime.html', datetime_obj=version.created %}
            </td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
    {% else %}
      <p>{{ _('There are no versions available for this dataset') }}</p>
    {% endif %}
  {% endif %}

  {% if c.current_version %}
    {% if h.check_access('dataset_version_delete', {'dataset': pkg.id}) %}
      <button data-version-id="{{ c.current_version.id }}"
              data-version-name="{{ c.current_version.name }}"
              class="delete-version-btn btn btn-danger">
        {{ _('Delete Version') }}
      </button>
    {% endif %}

    {% if h.check_access('dataset_version_create', {'dataset': pkg.id}) %}
    <button data-version-id="{{ c.current_version.id }}"
            data-version-name="{{ c.current_version.name }}"
            class="promote-version-btn btn btn-primary pull-right">
        {{ _('Promote Version') }}
    </button>
    <button type="button" class="btn btn-primary pull-right" data-toggle="modal" data-target="#updateVersionModal">
      {{ _('Edit Version Info') }}
    </button>
    {% snippet 'package/snippets/update_version.html' %}
    {% endif %}

  {% elif not c.revision_date %}
    {% if h.check_access('dataset_version_create', {'dataset': pkg.id}) %}
      <!-- Button trigger modal -->
      <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#createVersionModal">
        {{ _('Create Version') }}
      </button>

      {% snippet 'package/snippets/create_version.html' %}

    {% endif %}
    {% if h.check_access('dataset_versions_diff', {'dataset': pkg.id}) %}
      <button type="button" class="btn btn-secondary" data-toggle="modal" data-target="#compareVersionsModal" />
        {{ _('Compare Versions') }}
      </button>

      {% snippet 'package/snippets/compare_versions.html', pkg=pkg %}
    {% endif %}
  {% endif %}

</div>

ckanext/versions/templates/package/snippets/versions_select_options.html
{% if include_current %}
  <option value="current" {% if selected_id == 'current' %}selected="selected"{% endif %}>
  {{ _('[Current live version]') }}
  </option>
{% endif %}

{% for version in versions %}
  <option value="{{ version.id }}" {% if version.id == selected_id %}selected="selected"{% endif %}>
    {{ version.name }} - {{ h.render_datetime(version.created, with_hours=True)}}
  </option>
{% endfor %}

ckanext/versions/templates/package/version_changes.html
{% extends "package/base.html" %}

{% block subtitle %}{{ pkg_dict.name }} {{ g.template_title_delimiter }} Changes {{ g.template_title_delimiter }} {{ super() }}{% endblock %}

{% block breadcrumb_content_selected %}{% endblock %}

{% block breadcrumb_content %}
  {{ super() }}
  <li>{% link_for _('Changes'), named_route='versions.changes', id=pkg_dict.name %}</li>
{% endblock %}

{% block primary %}
  <article class="module">
    <div class="module-content">
      {% block package_changes_header %}
        <h1 class="page-heading">{{ _('Changes') }}</h1>
      {% endblock %}

      <form id="range_form" action="" data-module="select-switch" data-module-target="" class="form-inline">
      View changes from
        <select class="form-control select-time" form="range_form" name="version_id_1">
          {% snippet 'package/snippets/versions_select_options.html', versions=versions, selected_id=version_id_1 %}
        </select> to
        <select class="form-control select-time" form="range_form" name="version_id_2">

          {% snippet 'package/snippets/versions_select_options.html', versions=versions, selected_id=version_id_2, include_current=True %}
        </select>
      </form>

      <hr/>

      {% if diff %}
        {% snippet "package/snippets/change_item.html", diff=diff %}

        <input type="button" data-module="metadata-button" data-module-target="" class="btn" value="Show metadata diff" id="metadata_button"></input>
        <div id="metadata_diff" style="display:none;">
          <pre>
            {{ diff.diff|safe }}
          </pre>
        </div>
      {% endif %}

    </div>
  </article>

{% resource 'versions/metadata-button.js' %}  
{% resource 'versions/dataset_versions.css' %}  

{% endblock %}

{% block secondary %}{% endblock %}

ckanext/versions/templates/snippets/changes/extension_fields.html
<li>
  <p>
    {{ _('Changed value of field <q>{key}</q> to <q>{value}</q> in
        {pkg_link}').format(
        pkg_link = '<a href="{pkg_url}">{pkg_name}</a>'.format(
          pkg_url = h.url_for(controller='package',
                              action='read', id=change.pkg_id),
          pkg_name = change.title
        )|safe,
        key = change.key,
        value = change.value
    )}}
  </p>
</li>

ckanext/versions/templates/snippets/changes/maintainer.html
<li>
  <p>
    {% if change.method == "change" %}

      {{ _('Set maintainer of {pkg_link} to {new_maintainer}
        (previously {old_maintainer})').format(
            pkg_link = '<a href="{pkg_url}">{pkg_name}</a>'.format(
              pkg_url = h.url_for(controller='package',
                                  action='read', id=change.pkg_id),
              pkg_name = change.title
            )|safe,
            new_maintainer = change.new_maintainer,
            old_maintainer = change.old_maintainer
        ) }}

    {% elif change.method == "add" %}

      {{ _('Set maintainer of {pkg_link} to
          {new_maintainer}').format(
            pkg_link = '<a href="{pkg_url}">{pkg_name}</a>'.format(
              pkg_url = h.url_for(controller='package',
                                  action='read', id=change.pkg_id),
              pkg_name = change.title
            )|safe,
            new_maintainer = change.new_maintainer
      ) }}

    {% elif change.method == "remove" %}

      {{ _('Removed maintainer from {pkg_link}').format(
          pkg_link = '<a href="{pkg_url}">{pkg_name}</a>'.format(
            pkg_url = h.url_for(controller='package',
                                action='read', id=change.pkg_id),
            pkg_name = change.title
          )|safe
      ) }}

    {% else %}

      {{ _('No fields were updated. See the metadata diff for more details.') }}

    {% endif %}
  </p>
</li>

ckanext/versions/templates/snippets/changes/maintainer_email.html
<li>
  <p>
    {% if change.method == "change" %}

      {{ _('Set maintainer email of {pkg_link} to {new_email}
           (previously {old_email})').format(
             pkg_link = '<a href="{pkg_url}">{pkg_name}</a>'.format(
               pkg_url = h.url_for(controller='package',
                                   action='read', id=change.pkg_id),
               pkg_name = change.title
             )|safe,
             new_email = '<a href="{new_maintainer_email_link}">{new_maintainer_email}</a>'.format(
               new_maintainer_email = change.new_maintainer_email,
               new_maintainer_email_link = "mailto:" + change.new_maintainer_email
             )|safe,
             old_email = '<a href="{old_maintainer_email_link}">{old_maintainer_email}</a>'.format(
               old_maintainer_email = change.old_maintainer_email,
               old_maintainer_email_link = "mailto:" + change.old_maintainer_email
             )|safe
      ) }}

    {% elif change.method == "add" %}

      {{ _('Set maintainer email of {pkg_link} to {new_email}').format(
            pkg_link = '<a href="{pkg_url}">{pkg_name}</a>'.format(
              pkg_url = h.url_for(controller='package',
                                  action='read', id=change.pkg_id),
              pkg_name = change.title
            )|safe,
            new_email = '<a href="{new_maintainer_email_link}">{new_maintainer_email}</a>'.format(
              new_maintainer_email = change.new_maintainer_email,
              new_maintainer_email_link = "mailto:" + change.new_maintainer_email
            )|safe
      ) }}

    {% elif change.method == "remove" %}

      {{ _('Removed maintainer email from {pkg_link}').format(
          pkg_link = '<a href="{pkg_url}">{pkg_name}</a>'.format(
            pkg_url = h.url_for(controller='package',
                                action='read', id=change.pkg_id),
            pkg_name = change.title
          )|safe
      ) }}

    {% else %}

      {{ _('No fields were updated. See the metadata diff for more details.') }}

    {% endif %}
  </p>
</li>

ckanext/versions/templates/snippets/changes/name.html
<li>
  <p>
    {{ _('Moved {pkg_link} from {old_link} to {new_link}').format(
          pkg_link = '<a href="{pkg_url}">{pkg_name}</a>'.format(
            pkg_url = h.url_for(controller='package',
                                action='read', id=change.pkg_id),
            pkg_name = change.title
          )|safe,
          old_link = '<a href="{old_url}">{old_url}</a>'.format(
            old_url = h.url_for(qualified=True,
              controller='package', action='read', id=change.old_name)
          )|safe,
          new_link = '<a href="{new_url}">{new_url}</a>'.format(
            new_url = h.url_for(qualified=True,
              controller='package', action='read', id=change.new_name)
          )|safe
    ) }}
  </p>
</li>

ckanext/versions/templates/snippets/changes/new_file.html
<li>
  <p>
    {{ _('Uploaded a new file to resource {resource_link} in {pkg_link}').format(
          pkg_link = '<a href="{pkg_url}">{pkg_name}</a>'.format(
            pkg_url = h.url_for(controller='package',
                                action='read', id=change.pkg_id),
            pkg_name = change.title
          )|safe,
          resource_link = '<a href="{resource_url}">{resource_name}</a>'.format(
            resource_url = h.url_for(qualified=True, controller='package',
                                      action='resource_read', id=change.pkg_id,
                                      resource_id = change.resource_id),
            resource_name = change.resource_name
          )|safe
    ) }}
  </p>
</li>